:Version: 4.1.1
:toc: macro
:toc-title: 目次
:toclevels: 4

= プリロール広告ガイド AMoAd SDK {version} Guide for iOS

NOTE: プリロール広告の概要については、link:Overview_preroll.asciidoc[こちら]をご参照ください。

NOTE: SDKのインストールについてはlink:../Install/Install.asciidoc[こちら]をご参照ください。

NOTE: モジュールのダウンロードはこちら（link:https://github.com/amoad/amoad-ios-sdk/releases/latest[安定版]/link:https://github.com/amoad/amoad-ios-sdk/releases#[最新版]）からお願いします。

NOTE: サンプルコードが/Samples/AMoAdPreRollにありますので、管理画面から取得したsidを入力して動かしてください。

toc::[]

:numbered:
:sectnums:

== 広告を表示する

=== 実装の流れ

. 管理画面から発行されるsidを指定してモジュールを登録します。 +
[source,objective-c]
[AMoAdNativePreRoll prepareAdWithSid:kSid];

. 広告分析情報を作成する。 +
[source,objective-c]
  NSString *report_id = @"ABCD";
  NSString *value1 = @"ABCD";
  AMoAdAnalytics *analytics = [[AMoAdAnalytics alloc] initWithReportId:report_id];
  analytics.publisherParam = @{@"key1":value1};

. 広告を画面に表示する。 +
[source,objective-c]
[AMoAdNativePreRoll renderAdWithSid:kSid tag:kTag view:self.view analytics:analytics completion:nil];

=== 実装例

.ViewController.m
[source,objective-c]
----
#import "ViewController.h"
#import "AMoAdNativePreRoll.h"
#import "AMoAdLogger.h"

static NSString *const kSid = @"管理画面から取得したプリロール広告のsidを指定してください";
static NSString *const kTag = @"UserPreRollAd";

@interface ViewController ()
@property (nonatomic,readwrite,strong) UIButton *userBtn;
@end

@implementation ViewController

- (void)viewDidLoad {
  [super viewDidLoad];

  // [SDK] 広告分析情報を生成する
  //   => ご利用の際は担当営業までお問い合わせください。利用しない場合は、nilを指定してください。
  NSString *report_id = @"ABCD";  // レポートを細分化するためのID
  NSString *value1 = @"ABCD";  // パブリッシャ様が任意に指定できる分析用パラメタ文字列
  NSString *value2 = @"ABCD";  // パブリッシャ様が任意に指定できる分析用パラメタ文字列
  NSString *value3 = @"ABCD";  // パブリッシャ様が任意に指定できる分析用パラメタ文字列

  AMoAdAnalytics *analytics = [[AMoAdAnalytics alloc] initWithReportId:report_id];
  analytics.publisherParam = @{@"key1":value1,@"key2":value2,@"key3":value3};

  // [SDK] 広告準備
  [AMoAdNativePreRoll prepareAdWithSid:kSid];

  self.view.hidden = YES; // 広告取得成功まで非表示にする（推奨）

  // [SDK] プリロール広告を描画する
  [AMoAdNativePreRoll renderAdWithSid:kSid tag:kTag view:self.view analytics:analytics completion:^(NSString *sid, NSString *tag, UIView *view, AMoAdResult state) {
    switch (state) {
      case AMoAdResultSuccess:
        self.view.hidden = NO;  // 広告取得成功後、表示する（推奨）
        NSLog(@"広告受信成功:sid=%@,tag=%@", sid, tag);
        break;
      case AMoAdResultFailure:
        NSLog(@"広告受信失敗:sid=%@,tag=%@", sid, tag);
        break;
      case AMoAdResultEmpty:
        NSLog(@"配信する広告が無い:sid=%@,tag=%@", sid, tag);
        break;
    };
  }];

  // 画面下から92pxまではパブリッシャ様固有のViewを追加することが可能です。
  self.userBtn = [[UIButton alloc] initWithFrame:CGRectMake(0, [UIScreen mainScreen].bounds.size.height - 50, 155, 34)];
  [self.userBtn setTitle:@"本編へ進む" forState:UIControlStateNormal];
  [self.userBtn setTitleColor:[UIColor blueColor] forState:UIControlStateNormal];
  [self.userBtn setTitleColor:[UIColor redColor] forState:UIControlStateHighlighted];
  [self.view addSubview:self.userBtn];
}

// 回転対応：iOS 8.0未満のときのみ呼び出される（iOS 8.0以上では呼び出されない）
- (void)willRotateToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation duration:(NSTimeInterval)duration {
  // [SDK] 再レイアウトする
  [AMoAdNativePreRoll layoutAdWithSid:kSid tag:kTag];

  // パブリッシャ様固有ビューを再レイアウトする
  dispatch_async(dispatch_get_main_queue(), ^{
    self.userBtn.frame = CGRectMake(0, self.view.bounds.size.height - 50, 155, 34);
  });
}

// 回転対応：iOS 8.0以上のときのみ呼び出される
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id<UIViewControllerTransitionCoordinator>)coordinator {
  // [SDK] 再レイアウトする
  [AMoAdNativePreRoll layoutAdWithSid:kSid tag:kTag];

  // パブリッシャ様固有ビューを再レイアウトする
  dispatch_async(dispatch_get_main_queue(), ^{
    self.userBtn.frame = CGRectMake(0, self.view.bounds.size.height - 50, 155, 34);
  });
}

@end
----

== API詳細
=== NativePreRollクラス

==== prepareAdWithSid関数
管理画面から発行されるsidに紐づく広告情報を登録します。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |NSString 2+|管理画面から発行されるsidを設定してください
|===

==== renderAdWithSid関数
広告を画面に表示する。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |NSString 2+|管理画面から発行されるsidを設定してください
|tag |NSString 2+|同じsidを複数のViwで使用する場合,一意に管理する為に使用する
|containerView |UIView 2+|広告を乗せるビュー
|analytics |AMoAdAnalytics 2+|広告分析用データ
|completion |^(NSString *sid, NSString *tag, UIView *view, AMoAdResult state)  2+|コールバック
|===

=== Analyticsクラス
==== constructor
広告レポートIDを設定します。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|reportId |String 2+|広告レポートID
|===

==== メンーバ変数
広告分析情報を設定します。
[options="header"]
|===
|変数名 |Type 2+|Value
|reportParam |NSMutableDictionary 2+|キー＆バーリュ
|===

== その他の実装について

=== ログ・トレースの出力方法

link:../Common/Logger.md[ロギング・トレース機能]
