:Version: 4.4.0
:toc: macro
:toc-title: 目次
:toclevels: 4

= インタースティシャル（全画面）広告ガイド AMoAd SDK {version} Guide for iOS

NOTE: インタースティシャル広告の概要については、link:../Interstitial/Guide.asciidoc[こちら]をご参照ください。

NOTE: SDKのインストールについてはlink:../Install/Install.asciidoc[こちら]をご参照ください。

NOTE: モジュールのダウンロードはこちら（link:https://github.com/amoad/amoad-ios-sdk/releases/latest[安定版]/link:https://github.com/amoad/amoad-ios-sdk/releases#[最新版]）からお願いします。

NOTE: サンプルコードが/Samples/DisplayInterstitial/にありますので、管理画面から取得したsidを入力して動かしてください。

toc::[]

:numbered:
:sectnums:

== 広告を表示するスクリプト

=== コーディングの流れ

. 管理画面から発行されるsidを指定してモジュールを登録します。 +
`[AMoAdInterstitial registerAdWithSid:kSid];`
. パネル画像をUIImageオブジェクトで設定します。 +
`[AMoAdInterstitial setPortraitPanelWithSid:kSid image:panelImage];`
. 広告面をクリックできるかどうかを設定する：デフォルトはYES +
`[AMoAdInterstitial setDisplayWithSid:kSid clickable:NO];`
. 確認ダイアログを表示するかどうかを設定する：デフォルトはYES +
`[AMoAdInterstitial setDialogWithSid:kSid shown:NO];`
. 広告を表示したいタイミングで、以下のメソッドを呼び出します。 +
`[AMoAdInterstitial showAdWithSid:kSid completion:completion];`

TIP: パネル以外の画像も設定できます。以下を参照してください。
画像のサイズについては、
link:../Interstitial/Guide.asciidoc[こちら]をご参照ください。

=== コーディング例

.ViewController
[source,objc]
----
//
//  ViewController.m
//  AMoAdInterstitialAdSample
//
//  Created by AMoAd on 2016/04/25.
//  Copyright (c) 2016年 AMoAd. All rights reserved.
//

#import "ViewController.h"
#import "AMoAdInterstitial.h" // [SDK] インタースティシャル用ヘッダ
#import "AMoAdLogger.h"   // [SDK] ロガー

// [SDK] 管理画面から取得したsidを入力してください
static NSString *const kSid = @"62056d310111552c000000000000000000000000000000000000000000000000";

@implementation ViewController

- (void)viewDidLoad {
  [super viewDidLoad];

  // [SDK] ログ出力の設定
  [AMoAdLogger sharedLogger].logging = YES;

  // [SDK] トレース出力の設定
  [AMoAdLogger sharedLogger].trace = YES;

  // [SDK] カスタマイズする画像を準備する（標準の画像で良い場合はnilを指定する）
  UIImage *portraitPanelImage = [UIImage imageNamed:@"user_panel.png"]; // Portraitパネル画像（310x380）
  UIImage *landscapePanelImage = nil;     // Landscapeパネル画像（380x310）
  UIImage *linkButtonImage = nil;         // リンクボタン画像（280x50）
  UIImage *linkButtonHighlighted = nil;   // リンクボタン画像Highlight（280x50）
  UIImage *closeButtonImage = nil;        // 閉じるボタン画像（40x40）
  UIImage *closeButtonHighlighted = nil;  // 閉じるボタン画像Highlight（40x40）

  // [SDK] インタースティシャル広告の準備
  [AMoAdInterstitial registerAdWithSid:kSid];

  // [SDK] 画像を設定する
  [AMoAdInterstitial setPortraitPanelWithSid:kSid image:portraitPanelImage];
  [AMoAdInterstitial setLandscapePanelWithSid:kSid image:landscapePanelImage];
  [AMoAdInterstitial setLinkButtonWithSid:kSid image:linkButtonImage highlighted:linkButtonHighlighted];
  [AMoAdInterstitial setCloseButtonWithSid:kSid image:closeButtonImage highlighted:closeButtonHighlighted];

  // [SDK] 動作を設定する（iOS 7以下では必ず clickable:NO / shown:NO となります）
//  [AMoAdInterstitial setDisplayWithSid:kSid clickable:NO];  // 広告面をクリックできるかどうかを設定する：デフォルトはYES
//  [AMoAdInterstitial setDialogWithSid:kSid shown:NO]; // 確認ダイアログを表示するかどうかを設定する：デフォルトはYES
}

- (IBAction)showAd:(id)sender {
  // [SDK] インタースティシャル広告を表示する
  [AMoAdInterstitial showAdWithSid:kSid completion:^(NSString *sid, AMoAdInterstitialResult result) {
    switch (result) {
      case AMoAdInterstitialResultClick:
        NSLog(@"リンクボタンがクリックされたので閉じました");
        break;
      case AMoAdInterstitialResultClose:
        NSLog(@"閉じるボタンがクリックされたので閉じました");
        break;
      case AMoAdInterstitialResultDuplicated:
        NSLog(@"既に開かれているので開きませんでした");
        break;
      case AMoAdInterstitialResultCloseFromApp:
        NSLog(@"アプリから閉じられました");
        break;
      case AMoAdInterstitialResultFailure:
        NSLog(@"広告の取得に失敗しました");
        break;
    }
  }];
}

@end
----

=== API

link:../../Samples/DisplayInterstitial/AMoAdInterstitialAdSample/AMoAdInterstitialAdSample/AMoAdInterstitial.h[AMoAd Interstitial API]

link:../../Samples/DisplayInterstitial/AMoAdInterstitialAdSample/AMoAdInterstitialAdSample/AMoAdLogger.h[AMoAd Logger API] (link:../Common/Logger.md[ロギング・トレース機能について])
