:Version: 1.0.0
:toc: macro
:toc-title: 目次
:toclevels: 4

= AMoAd Cocos2d-x Module {version} Guide

toc::[]

:numbered:
:sectnums:

== 概要

=== はじめに
AMoAd Cocos2d-x Module（以下、モジュール）を適用することで、Cocos2d-xアプリにAMoAdネットワークの広告を表示することが可能になります。

TIP: 広告の表示には別途、AMoAd SDKが必要です。

=== 対象サービス

[options="header"]
|===
|サービス |種類 |サイズ
|link:Display.asciidoc[バナー広告] |画像、HTML |320×50、320×100、300×250、728×90
|link:Interstitial.asciidoc[インタースティシャル（全画面）広告] |画像 |300x250
|ネイティブ広告 |未対応 |未対応
|===

== パッケージのダウンロード
こちらのURLより取得できます。

link:https://github.com/amoad/amoad-ios-sdk/releases/latest[安定版ダウンロードページ] ::
リリース時は、こちらの使用をお勧めします。

link:https://github.com/amoad/amoad-ios-sdk/releases#[最新版ダウンロードページ] ::
開発中のベータ版、アルファ版などが含まれます。

TIP: /Cocos2dxModule/AMoAdCocos2dxModule.zip

== モジュールの適用手順
以下の手順でモジュールをCocos2d-xアプリに適用します。

. AMoAdCocos2dxModule.zipをダブルクリックします。
. 解答されたファイルをプロジェクトに追加します。

[horizontal]
AMoAdCocos2dxModule.h::
モジュールのメインヘッダ
AMoAdCocos2dxModule.mm::
iOS版モジュールブリッジの実装
AMoAdCocos2dxModule.cpp::
Android版モジュールブリッジの実装
com/amoad/cocos2dx/AMoAdCocos2dxModule.java::
Android版モジュールブリッジの実装

上記のファイルが揃っていれば、モジュールの適用は完了です。

== ビルド、環境設定
AMoAd SDK for iOS/Androidを導入して、通常の手順にてCocos2d-xプロジェクトのビルドを行ってください。

NOTE: SDKの導入については、こちら（link:../Install/Install.asciidoc[iOS版]
/link:https://github.com/amoad/amoad-android-sdk/blob/master/Documents/Setup.asciidoc[Android版]）をご参照ください。
