:Version: 1.2.0
:toc: macro
:toc-title: 目次
:toclevels: 4

= インタースティシャル（全画面）広告ガイド AMoAd Cocos2dx Module {version} Guide

NOTE: インタースティシャル広告の概要については、link:../Interstitial/Guide.asciidoc[こちら]をご参照ください。

NOTE: SDKのインストールについてはこちら（link:../Install/Install.asciidoc[iOS版]/link:https://github.com/amoad/amoad-android-sdk/blob/master/Documents/Setup.asciidoc[Android版]）をご参照ください。

NOTE: Cocos2d-xモジュールのインストールについてはlink:Guide.asciidoc[こちら]をご参照ください。

NOTE: ダウンロードはこちら（link:https://github.com/amoad/amoad-ios-sdk/releases/latest[安定版]/link:https://github.com/amoad/amoad-ios-sdk/releases#[最新版]）からお願いします。

toc::[]

:numbered:
:sectnums:

== 広告を表示するスクリプト

=== スクリプトの流れ

. 管理画面から発行されるsidを指定してregisterInterstitialAd()メソッドでモジュールを登録します。 +
`AMoAdCocos2dxModule::registerInterstitialAd (sid);`
. 横・縦画面のパネル画像をファイル名で設定します。 +
`AMoAdCocos2dxModule::setInterstitialPortraitPanel (sid, imageName);`
`AMoAdCocos2dxModule::setInterstitialLandscapePanel (sid, imageName);`
. 広告面をクリックできるかどうかを設定する(default:true) +
`AMoAdCocos2dxModule::setInterstitialDisplayClickable (sid, clickable);`
. 確認ダイアログを表示するかどうかを設定する(default:true) +
`AMoAdCocos2dxModule::setInterstitialDialogShown (sid, shown);`
. ボタン押下時など広告の表示を開始したいタイミングで、showInterstitialAd()メソッドを呼び出します。 +
`AMoAdCocos2dxModule::showInterstitialAd (sid);`

TIP: パネル以外の画像を標準画像から変える場合は、担当営業までお問合せください

=== スクリプト例

.管理画面から発行されるsidを設定してください
[source,cpp]
----
static const char* SID = "管理画面から発行されるsidを設定してください";
----

.インタースティシャル（全画面）広告を登録する
[source,cpp]
----
AMoAdCocos2dxModule::registerInterstitialAd(SID);
----

.横・縦画面のパネル画像をファイル名で指定する
[source,cpp]
----
AMoAdCocos2dxModule::setInterstitialPortraitPanel(SID, "縦画面のパネルに使用する画像ファイル名");
AMoAdCocos2dxModule::setInterstitialLandscapePanel(SID, "横画面のパネルに使用する画像ファイル名");
----

.広告面をクリックできるかどうかを設定する
[source,cpp]
----
AMoAdCocos2dxModule::setInterstitialDisplayClickable(SID, clickable);
----

.確認ダイアログを表示するかどうかを設定する
[source,cpp]
----
AMoAdCocos2dxModule::setInterstitialDialogShown(SID, shown);
----

.インタースティシャル（全画面）広告を表示する
[source,cpp]
----
AMoAdCocos2dxModule::showInterstitialAd(SID);
----

=== パラメタの説明
==== AMoAdCocos2dxModule::registerInterstitialAd()
管理画面から発行されるsidに紐づく広告情報を登録します。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |string 2+|管理画面から発行されるsidを設定してください
|===

==== AMoAdCocos2dxModule::setInterstitialPortraitPanel()
sidを指定して縦画面のパネル画像を設定します。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |string 2+|管理画面から発行されるsidを設定してください
|imageName |string 2+|パネルに使用する画像ファイル名
|===

==== AMoAdCocos2dxModule::setInterstitialLandscapePanel()
sidを指定して横画面のパネル画像を設定します。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |string 2+|管理画面から発行されるsidを設定してください
|imageName |string 2+|パネルに使用する画像ファイル名
|===

==== AMoAdCocos2dxModule::setInterstitialDisplayClickable()
広告面をクリックできるかどうかを設定する。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |string 2+|管理画面から発行されるsidを設定してください
|clickable |boolean 2+|広告面をクリックできるかどうか(default:true)
|===

==== AMoAdCocos2dxModule::setInterstitialDialogShown()
確認ダイアログを表示するかどうかを設定する。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |string 2+|管理画面から発行されるsidを設定してください
|shown |boolean 2+|確認ダイアログを表示するかどうか(default:true)
|===

==== AMoAdCocos2dxModule::showInterstitialAd()
sidを指定して広告の表示を行います。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |string 2+|管理画面から発行されるsidを設定してください
|===

==== AMoAdCocos2dxModule::closeInterstitialAd()
sidを指定して広告を閉じます。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |string 2+|管理画面から発行されるsidを設定してください
|===

TIP: リンクボタン、閉じるボタンが押された時は自動的に閉じるので、このメソッドを呼び出す必要はありません。
