:Version: 1.0.1
:toc: macro
:toc-title: 目次
:toclevels: 4

= AMoAd Unity Plugin {version} Guide

toc::[]

:numbered:
:sectnums:

== 広告を表示するスクリプト

=== スクリプトの流れ

. 管理画面から発行されるsid、広告サイズ、表示位置などを指定してRegister()メソッドでプラグインを登録します。 +
`AMoAdUnityPlugin.Register (sid, ...);`
. Awake()、Start()など広告の表示を開始したいタイミングで、Show()メソッドを呼び出します。 +
`AMoAdUnityPlugin.Show (sid);`
. 広告を消したいタイミングで、Hide()メソッドを呼び出します。 +
`AMoAdUnityPlugin.Hide (sid);`
. メモリ使用量が気になるときはHide()の代わりに、Dispose()メソッドを呼び出してください（Show()で再表示できます）。 +
`AMoAdUnityPlugin.Dispose (sid);`

TIP: 広告の切り替え（ローテーション）は、管理画面で指定された秒数で行なわれます。プラグインで指定することはできません。

=== スクリプト例

.AMoAdUnityPluginSample.cs
[source,csharp]
----
public class AMoAdUnityPluginSample : MonoBehaviour {

  private static string SID = "管理画面から発行されるsidを設定してください";

  static AMoAdUnityPluginSample () {
    AMoAdUnityPlugin.Register (
      sid:SID,
      bannerSize:AMoAdUnityPlugin.BannerSize.B320x50,
      hAlign:AMoAdUnityPlugin.HorizontalAlign.Center,
      vAlign:AMoAdUnityPlugin.VerticalAlign.Bottom,
      adjustMode:AMoAdUnityPlugin.AdjustMode.Responsive,
      rotateTrans:AMoAdUnityPlugin.RotateTransition.FlipFromLeft,
      clickTrans:AMoAdUnityPlugin.ClickTransition.Jump,
      imageName:"b640_100.gif"
      );
  }

  void Awake () {
    AMoAdUnityPlugin.Show (SID);
  }
}
----

=== パラメタの説明
==== AMoAdUnityPlugin.Register()
管理画面から発行されるsidに紐づく広告情報を登録します。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |string 2+|管理画面から発行されるsidを設定してください
.5+|bannerSize .5+|AMoAdUnityPlugin .BannerSize 2+|広告サイズ
|B320x50 |320×50
|B320x100 |320×100
|B300x250 |300×250
|B728x90 |728×90 (iPad用)
.5+|hAlign .5+|AMoAdUnityPlugin .HorizontalAlign 2+|水平方向の表示位置
|None |なし（x座標指定）
|Left |左寄せ
|Center |中央寄せ
|Right |右寄せ
.5+|vAlign .5+|AMoAdUnityPlugin .VerticalAlign 2+|垂直方向の表示位置
|None |なし（y座標指定）
|Left |上寄せ
|Middle |中央寄せ
|Right |下寄せ
.3+|adjustMode .3+|AMoAdUnityPlugin .AdjustMode 2+|広告サイズの調整
|Fixed |固定
|Responsive |レスポンシブ（デフォルト）
.6+|rotateTrans .6+|AMoAdUnityPlugin .RotateTransition 2+|広告ローテーション時のトランジションを設定する（iOS用）
|None |トランジション「なし」（デフォルト）
|CurlUp |トランジション「巻き上げ」
|CurlDown |トランジション「巻き下げ」
|FlipFromLeft |トランジション「左フリップ」
|FlipFromRight |トランジション「右フリップ」
.3+|clickTrans .3+|AMoAdUnityPlugin .ClickTransition 2+|広告クリック時のトランジションを設定する（iOS用）
|None |トランジション「なし」（デフォルト）
|Jump |トランジション「ジャンプ」
|imageName |string 2+|初期表示画像ファイル名（Androidアプリを作成する場合は、アルファベットの小文字で始まる名前）
|x |int 2+|x座標（hAlignがNoneのときのみ有効）
|y |int 2+|y座標（vAlignがNoneのときのみ有効）
.6+|androidRotateTrans .6+|AMoAdUnityPlugin .AndroidRotateTransition 2+|広告ローテーション時のトランジションを設定する（Android用）
|None |トランジション「なし」（デフォルト）
|Alpha |トランジション「透過」
|Rotate |トランジション「回転」
|Scale |トランジション「拡大」
|Translate |トランジション「スライド・アップ」
.3+|androidClickTrans .3+|AMoAdUnityPlugin .AndroidClickTransition 2+|広告クリック時のトランジションを設定する（Android用）
|None |トランジション「なし」（デフォルト）
|Jump |トランジション「ジャンプ」
|===

TIP: 広告サイズの調整にレスポンシブを選択すると、端末のサイズに合わせて広告が拡大縮小します。

TIP: Androidアプリをビルドする場合は、対応しているアニメーションが異なりますので、androidRotateTrans、androidClickTransをご使用ください。

==== AMoAdUnityPlugin.Show()
sidを指定して広告の表示を行います。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |string 2+|管理画面から発行されるsidを設定してください
|===

==== AMoAdUnityPlugin.Hide()
sidを指定して広告を消します。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |string 2+|管理画面から発行されるsidを設定してください
|===

==== AMoAdUnityPlugin.Dispose()
メモリ容量が気になる場合、広告を消してViewのリソースを解放します。AMoAdUnityPlugin.Show()メソッドで再表示できます。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |string 2+|管理画面から発行されるsidを設定してください
|===

TIP: AMoAdUnityPlugin.Show()メソッド呼び出し時、Viewがなければ作成します。同じsidの広告を同じ画面に複数、置くことはできません。

== サンプルアプリケーションの使用方法
=== AMoAdUnityPluginSample

link:https://github.com/amoad/amoad-ios-sdk/blob/master/Samples/UnityPlugin/AMoAdUnityPluginSample[サンプルコード]

.AMoAdUnityPluginSample.cs
[source,csharp]
----
public class AMoAdUnityPluginSample : MonoBehaviour {

  private static string SID = "管理画面から発行されるsidを設定してください";

  static AMoAdUnityPluginSample () {
    AMoAdUnityPlugin.Register (
      sid:SID,
      bannerSize:AMoAdUnityPlugin.BannerSize.B320x50,
      hAlign:AMoAdUnityPlugin.HorizontalAlign.Center,
      vAlign:AMoAdUnityPlugin.VerticalAlign.Bottom,
      adjustMode:AMoAdUnityPlugin.AdjustMode.Responsive,
      rotateTrans:AMoAdUnityPlugin.RotateTransition.FlipFromLeft,
      clickTrans:AMoAdUnityPlugin.ClickTransition.Jump,
      imageName:"b640_100.gif"
      );
  }

  void Awake () {
    AMoAdUnityPlugin.Show (SID);
  }
}
----

. AMoAdUnityPluginSample.csのSIDに管理画面から発行されるsidを入力してください
. Register()のパラメタ、bannerSizeに管理画面に指定した広告サイズを記入してください
. その他、表示設定を変えたいときはRegister()メソッドのパラメタを変更してください
. link:Guide.asciidoc[導入ガイド]の手順に従いプラグイン、SDKの導入、ビルドを行ってください

表示設定の詳細は上記、パラメタの説明をご参照ください。
