:Version: 1.0.2
:toc: macro
:toc-title: 目次
:toclevels: 4

= インタースティシャル（全画面）広告ガイド AMoAd Unity Plugin {version} Guide

NOTE: インタースティシャル広告の概要については、link:../Interstitial/Guide.asciidoc[こちら]をご参照ください。

NOTE: SDKのインストールについてはこちら（link:../Install/Install.asciidoc[iOS版]/link:https://github.com/amoad/amoad-android-sdk/blob/master/Documents/Setup.asciidoc[Android版]）をご参照ください。

NOTE: Unityプラグインのインストールについてはlink:Guide.asciidoc[こちら]をご参照ください。

NOTE: ダウンロードはこちら（link:https://github.com/amoad/amoad-ios-sdk/releases/latest[安定版]/link:https://github.com/amoad/amoad-ios-sdk/releases#[最新版]）からお願いします。

NOTE: サンプルコードが/Samples/UnityPlugin/にありますので、管理画面から取得したsidを入力して動かしてください。

toc::[]

:numbered:
:sectnums:

== 広告を表示するスクリプト

=== スクリプトの流れ

. 管理画面から発行されるsidを指定してRegisterInterstitialAd()メソッドでプラグインを登録します。 +
`AMoAdUnityPlugin.RegisterInterstitialAd (sid);`
. 縦・横画面のパネル画像を設定します。 +
`AMoAdUnityPlugin.SetInterstitialPortraitPanel (sid, imageName);`
`AMoAdUnityPlugin.SetInterstitialLandscapePanel (sid, imageName);`
. 広告面をクリックできるかどうかを設定する：デフォルトはtrue +
`AMoAdUnityPlugin.SetInterstitialDisplayClickable (sid, clickable);`
. 確認ダイアログを表示するかどうかを設定する：デフォルトはtrue +
`AMoAdUnityPlugin.SetInterstitialDialogShown (sid, shown);`
. ボタン押下時など広告の表示を開始したいタイミングで、ShowInterstitialAd()メソッドを呼び出します。 +
`AMoAdUnityPlugin.ShowInterstitialAd (sid);`

TIP: パネル以外の画像を標準画像から変える場合は、担当営業までお問合せください

=== スクリプト例

.AMoAdUnityPluginInterstitialSample.cs
[source,csharp]
----
public class AMoAdUnityPluginInterstitialSample : MonoBehaviour {

  private static string SID = "管理画面から発行されるsidを設定してください";
  private static string PORTRAIT_IMAGE_NAME = "パネルに使用する画像ファイル名";
  private static string LANDSCAPE_IMAGE_NAME = "パネルに使用する画像ファイル名";

  void Awake () {
    //広告準備
    AMoAdUnityPlugin.RegisterInterstitialAd (sid:SID);
    AMoAdUnityPlugin.SetInterstitialPortraitPanel (sid:SID, imageName:PORTRAIT_IMAGE_NAME);
    AMoAdUnityPlugin.SetInterstitialLandscapePanel (sid:SID, imageName:LANDSCAPE_IMAGE_NAME);
    //AMoAdUnityPlugin.SetInterstitialDisplayClickable (sid:SID, clickable:false);
    //AMoAdUnityPlugin.SetInterstitialDialogShown (sid:SID, shown:false);

    //広告表示
    AMoAdUnityPlugin.ShowInterstitialAd (SID);
  }
}
----

=== パラメタの説明
==== AMoAdUnityPlugin.RegisterInterstitialAd()
管理画面から発行されるsidに紐づく広告情報を登録します。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |string 2+|管理画面から発行されるsidを設定してください
|===

==== AMoAdUnityPlugin.SetInterstitialPortraitPanel()
sidを指定してパネル画像を設定します。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |string 2+|管理画面から発行されるsidを設定してください
|imageName |string 2+|縦画面のパネルに使用する画像ファイル名
|===

==== AMoAdUnityPlugin.SetInterstitialLandscapePanel()
sidを指定してパネル画像を設定します。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |string 2+|管理画面から発行されるsidを設定してください
|imageName |string 2+|横画面のパネルに使用する画像ファイル名
|===

==== AMoAdUnityPlugin.SetInterstitialDisplayClickable()
広告面をクリックできるかどうかを設定する。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |string 2+|管理画面から発行されるsidを設定してください
|clickable |boolean 2+|広告面をクリックできるかどうか(default:true)
|===

==== AMoAdUnityPlugin.SetInterstitialDialogShown()
確認ダイアログを表示するかどうかを設定する。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |string 2+|管理画面から発行されるsidを設定してください
|clickable |boolean 2+|確認ダイアログを表示するかどうか(default:true)
|===

==== AMoAdUnityPlugin.ShowInterstitialAd()
sidを指定して広告の表示を行います。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |string 2+|管理画面から発行されるsidを設定してください
|===

==== AMoAdUnityPlugin.CloseInterstitialAd()
sidを指定して広告を閉じます。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |string 2+|管理画面から発行されるsidを設定してください
|===

TIP: リンクボタン、閉じるボタンが押された時は自動的に閉じるので、このメソッドを呼び出す必要はありません。

== サンプルアプリケーションの使用方法
=== AMoAdUnityPluginInterstitialSample

link:../../Samples/UnityPlugin/AMoAdUnityPluginInterstitialSample[サンプルコード]

.AMoAdUnityPluginInterstitialSample.cs
[source,csharp]
----
public class AMoAdUnityPluginInterstitialSample : MonoBehaviour {

  private static string SID = "管理画面から発行されるsidを設定してください";
  private static string PORTRAIT_IMAGE_NAME = "パネルに使用する画像ファイル名";
  private static string LANDSCAPE_IMAGE_NAME = "パネルに使用する画像ファイル名";

  void Awake () {
    //広告準備
    AMoAdUnityPlugin.RegisterInterstitialAd (sid:SID);
    AMoAdUnityPlugin.SetInterstitialPortraitPanel (sid:SID, imageName:PORTRAIT_IMAGE_NAME);
    AMoAdUnityPlugin.SetInterstitialLandscapePanel (sid:SID, imageName:LANDSCAPE_IMAGE_NAME);
    //AMoAdUnityPlugin.SetInterstitialDisplayClickable (sid:SID, clickable:false);
    //AMoAdUnityPlugin.SetInterstitialDialogShown (sid:SID, shown:false);

    //広告表示
    AMoAdUnityPlugin.ShowInterstitialAd (SID);
  }
}
----

. AMoAdUnityPluginInterstitialSample.csのSIDに管理画面から発行されるsidを入力してください
. パネル画像を変えたいときはSetInterstitialPortraitPanel()または、SetInterstitialLandscapePanel()メソッドのimageNameを変更してください
. link:Guide.asciidoc[導入ガイド]の手順に従いプラグイン、SDKの導入、ビルドを行ってください
