platform :ios, '11.0'
target 'AMoAdSdkDemo' do
  use_frameworks!
  pod "AMoAd"
  pod "AMoAdMaxAdapter"
  pod "AMoAdAdMobAdapter"
  pod 'SnapKit'
  pod 'ObjectMapper'
  pod 'ReachabilitySwift'
end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
end

